//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ApproveMaterial {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApproveMaterial.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 ABC码 的本地化字符串。
        /// </summary>
        internal static string ABCCode {
            get {
                return ResourceManager.GetString("ABCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料号申请 的本地化字符串。
        /// </summary>
        internal static string ApplyMaterial {
            get {
                return ResourceManager.GetString("ApplyMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审批 的本地化字符串。
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审批时间 的本地化字符串。
        /// </summary>
        internal static string ApproveDateTime {
            get {
                return ResourceManager.GetString("ApproveDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审批人 的本地化字符串。
        /// </summary>
        internal static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审批人姓名 的本地化字符串。
        /// </summary>
        internal static string ApproverName {
            get {
                return ResourceManager.GetString("ApproverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审批成功 的本地化字符串。
        /// </summary>
        internal static string ApproveSuccessfully {
            get {
                return ResourceManager.GetString("ApproveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码原则 的本地化字符串。
        /// </summary>
        internal static string CodeRule {
            get {
                return ResourceManager.GetString("CodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审批意见 的本地化字符串。
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 hi {0}/r/n       您有一项料号申请({1})审批通过了，请登录系统进行查看，请登录系统进行审批,{2} 的本地化字符串。
        /// </summary>
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 hi {0}/r/n       你的料号申请({1})被驳回了，请登录系统进行查看,{2} 的本地化字符串。
        /// </summary>
        internal static string EmailBodyReject {
            get {
                return ResourceManager.GetString("EmailBodyReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 流程节点 的本地化字符串。
        /// </summary>
        internal static string FlowNodeName {
            get {
                return ResourceManager.GetString("FlowNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 其他分群码四 的本地化字符串。
        /// </summary>
        internal static string FourthGroupCode {
            get {
                return ResourceManager.GetString("FourthGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分群码 的本地化字符串。
        /// </summary>
        internal static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入审批意见 的本地化字符串。
        /// </summary>
        internal static string InputComments {
            get {
                return ResourceManager.GetString("InputComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否保税 的本地化字符串。
        /// </summary>
        internal static string IsBonded {
            get {
                return ResourceManager.GetString("IsBonded", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料号审批通过 的本地化字符串。
        /// </summary>
        internal static string MaterialApproveOK {
            get {
                return ResourceManager.GetString("MaterialApproveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料件分类 的本地化字符串。
        /// </summary>
        internal static string MaterialClass {
            get {
                return ResourceManager.GetString("MaterialClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 物料编码 的本地化字符串。
        /// </summary>
        internal static string MaterialId {
            get {
                return ResourceManager.GetString("MaterialId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料号申请驳回通知 的本地化字符串。
        /// </summary>
        internal static string MaterialRejectNotice {
            get {
                return ResourceManager.GetString("MaterialRejectNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中分类 的本地化字符串。
        /// </summary>
        internal static string MiddleClass {
            get {
                return ResourceManager.GetString("MiddleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 品名 的本地化字符串。
        /// </summary>
        internal static string ProductionName {
            get {
                return ResourceManager.GetString("ProductionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 驳回 的本地化字符串。
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 被驳回 的本地化字符串。
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 驳回成功 的本地化字符串。
        /// </summary>
        internal static string RejectOK {
            get {
                return ResourceManager.GetString("RejectOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审批结果 的本地化字符串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要审批的数据 的本地化字符串。
        /// </summary>
        internal static string SelectData {
            get {
                return ResourceManager.GetString("SelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 来源码 的本地化字符串。
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 规格 的本地化字符串。
        /// </summary>
        internal static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 步序 的本地化字符串。
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 次分类 的本地化字符串。
        /// </summary>
        internal static string SubClass {
            get {
                return ResourceManager.GetString("SubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料号审批 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 大分类 的本地化字符串。
        /// </summary>
        internal static string TopClass {
            get {
                return ResourceManager.GetString("TopClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 单位 的本地化字符串。
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
    }
}
