//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ApplyMaterial {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApplyMaterial.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 ABC码 的本地化字符串。
        /// </summary>
        internal static string ABCCode {
            get {
                return ResourceManager.GetString("ABCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料号审批 的本地化字符串。
        /// </summary>
        internal static string ApplyMaterial {
            get {
                return ResourceManager.GetString("ApplyMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保税性质 的本地化字符串。
        /// </summary>
        internal static string Bonded {
            get {
                return ResourceManager.GetString("Bonded", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 品牌 的本地化字符串。
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 抛送资料库 的本地化字符串。
        /// </summary>
        internal static string BuCode {
            get {
                return ResourceManager.GetString("BuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 涂层类型 的本地化字符串。
        /// </summary>
        internal static string CoatingType {
            get {
                return ResourceManager.GetString("CoatingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码原则 的本地化字符串。
        /// </summary>
        internal static string CodeRule {
            get {
                return ResourceManager.GetString("CodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户名称 的本地化字符串。
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 hi {0}/r/n       您有一项料号申请，请登录系统进行审批,{1} 的本地化字符串。
        /// </summary>
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 环保要求 的本地化字符串。
        /// </summary>
        internal static string EnvironmentalRequirement {
            get {
                return ResourceManager.GetString("EnvironmentalRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料号已经存在 的本地化字符串。
        /// </summary>
        internal static string ExistMaterial {
            get {
                return ResourceManager.GetString("ExistMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 其他分群码四 的本地化字符串。
        /// </summary>
        internal static string FourthGroupCode {
            get {
                return ResourceManager.GetString("FourthGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分群码 的本地化字符串。
        /// </summary>
        internal static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分群码不能为空 的本地化字符串。
        /// </summary>
        internal static string GroupCodeCanNotBlank {
            get {
                return ResourceManager.GetString("GroupCodeCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否保税 的本地化字符串。
        /// </summary>
        internal static string IsBonded {
            get {
                return ResourceManager.GetString("IsBonded", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 制造商代码 的本地化字符串。
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 制造商/品牌 的本地化字符串。
        /// </summary>
        internal static string ManufacturerBrand {
            get {
                return ResourceManager.GetString("ManufacturerBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料件分类 的本地化字符串。
        /// </summary>
        internal static string MaterialClass {
            get {
                return ResourceManager.GetString("MaterialClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 物料编码 的本地化字符串。
        /// </summary>
        internal static string MaterialId {
            get {
                return ResourceManager.GetString("MaterialId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 材料品名 的本地化字符串。
        /// </summary>
        internal static string MaterialProductName {
            get {
                return ResourceManager.GetString("MaterialProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 材料形态 的本地化字符串。
        /// </summary>
        internal static string MaterialProperty {
            get {
                return ResourceManager.GetString("MaterialProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料号类别 的本地化字符串。
        /// </summary>
        internal static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中分类 的本地化字符串。
        /// </summary>
        internal static string MiddleClass {
            get {
                return ResourceManager.GetString("MiddleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你无权发起审批，请联系管理员！ 的本地化字符串。
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您没有权限 的本地化字符串。
        /// </summary>
        internal static string NoAuth {
            get {
                return ResourceManager.GetString("NoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 找不到编码规则{0}的配置信息 的本地化字符串。
        /// </summary>
        internal static string NOTFoundCodeRule {
            get {
                return ResourceManager.GetString("NOTFoundCodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 制程 的本地化字符串。
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 品名 的本地化字符串。
        /// </summary>
        internal static string ProductionName {
            get {
                return ResourceManager.GetString("ProductionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 品名不能为空 的本地化字符串。
        /// </summary>
        internal static string ProductionNameCanNotBlank {
            get {
                return ResourceManager.GetString("ProductionNameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 品名 的本地化字符串。
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 产品号 的本地化字符串。
        /// </summary>
        internal static string ProductNO {
            get {
                return ResourceManager.GetString("ProductNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修模类型 的本地化字符串。
        /// </summary>
        internal static string RepairMoldType {
            get {
                return ResourceManager.GetString("RepairMoldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 版次 的本地化字符串。
        /// </summary>
        internal static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存并新增 的本地化字符串。
        /// </summary>
        internal static string SaveAndCreate {
            get {
                return ResourceManager.GetString("SaveAndCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择中分类 的本地化字符串。
        /// </summary>
        internal static string SelectMiddleClass {
            get {
                return ResourceManager.GetString("SelectMiddleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择次分类 的本地化字符串。
        /// </summary>
        internal static string SelectSubClass {
            get {
                return ResourceManager.GetString("SelectSubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择大分类 的本地化字符串。
        /// </summary>
        internal static string SelectTopClass {
            get {
                return ResourceManager.GetString("SelectTopClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 流水码 的本地化字符串。
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 来源码 的本地化字符串。
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 专案名称 的本地化字符串。
        /// </summary>
        internal static string SpecialName {
            get {
                return ResourceManager.GetString("SpecialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 规格型号 的本地化字符串。
        /// </summary>
        internal static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 规格型号不能为空 的本地化字符串。
        /// </summary>
        internal static string SpecificationCanNotBlank {
            get {
                return ResourceManager.GetString("SpecificationCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 次分类 的本地化字符串。
        /// </summary>
        internal static string SubClass {
            get {
                return ResourceManager.GetString("SubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 料号申请 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 大分类 的本地化字符串。
        /// </summary>
        internal static string TopClass {
            get {
                return ResourceManager.GetString("TopClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 单位 的本地化字符串。
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工件类型 的本地化字符串。
        /// </summary>
        internal static string WorkpieceType {
            get {
                return ResourceManager.GetString("WorkpieceType", resourceCulture);
            }
        }
    }
}
