//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Employee {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Employee.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 组织代码 的本地化字符串。
        /// </summary>
        internal static string ApplicationOrg {
            get {
                return ResourceManager.GetString("ApplicationOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 组织代码不能为空 的本地化字符串。
        /// </summary>
        internal static string ApplicationOrgCodeCanNotBlank {
            get {
                return ResourceManager.GetString("ApplicationOrgCodeCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除选中行？ 的本地化字符串。
        /// </summary>
        internal static string DeleteRecordQuestion {
            get {
                return ResourceManager.GetString("DeleteRecordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部门 的本地化字符串。
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部门编码 的本地化字符串。
        /// </summary>
        internal static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部门 的本地化字符串。
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 员工 的本地化字符串。
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string EmployeeEmail {
            get {
                return ResourceManager.GetString("EmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮箱不能为空 的本地化字符串。
        /// </summary>
        internal static string EmployeeEmailCanNotBlank {
            get {
                return ResourceManager.GetString("EmployeeEmailCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 英文名 的本地化字符串。
        /// </summary>
        internal static string EmployeeEnglishName {
            get {
                return ResourceManager.GetString("EmployeeEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工号 的本地化字符串。
        /// </summary>
        internal static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工号不能为空 的本地化字符串。
        /// </summary>
        internal static string EmployeeIDCanNotBlank {
            get {
                return ResourceManager.GetString("EmployeeIDCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 姓名不能为空 的本地化字符串。
        /// </summary>
        internal static string EmployeeNameCanNotBlank {
            get {
                return ResourceManager.GetString("EmployeeNameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string EmployeePhone {
            get {
                return ResourceManager.GetString("EmployeePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string EmpoyeeGender {
            get {
                return ResourceManager.GetString("EmpoyeeGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 性别不能为空 的本地化字符串。
        /// </summary>
        internal static string EmpoyeeGenderCanNotBlank {
            get {
                return ResourceManager.GetString("EmpoyeeGenderCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 女 的本地化字符串。
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 男 的本地化字符串。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 组织 的本地化字符串。
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 岗位 的本地化字符串。
        /// </summary>
        internal static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先保存数据 的本地化字符串。
        /// </summary>
        internal static string SaveDataFirst {
            get {
                return ResourceManager.GetString("SaveDataFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 员工 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
