//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.TipTopMaterial {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipTopMaterial.CostDataWSSoap")]
    public interface CostDataWSSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 type 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CostDataIn", ReplyAction="*")]
        ERP.TipTopMaterial.CostDataInResponse CostDataIn(ERP.TipTopMaterial.CostDataInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CostDataIn", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP.TipTopMaterial.CostDataInResponse> CostDataInAsync(ERP.TipTopMaterial.CostDataInRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CostDataInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CostDataIn", Namespace="http://tempuri.org/", Order=0)]
        public ERP.TipTopMaterial.CostDataInRequestBody Body;
        
        public CostDataInRequest() {
        }
        
        public CostDataInRequest(ERP.TipTopMaterial.CostDataInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CostDataInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string buCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dotype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ERP.TipTopMaterial.ArrayOfString XMLS;
        
        public CostDataInRequestBody() {
        }
        
        public CostDataInRequestBody(string type, string buCode, string dotype, ERP.TipTopMaterial.ArrayOfString XMLS) {
            this.type = type;
            this.buCode = buCode;
            this.dotype = dotype;
            this.XMLS = XMLS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CostDataInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CostDataInResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP.TipTopMaterial.CostDataInResponseBody Body;
        
        public CostDataInResponse() {
        }
        
        public CostDataInResponse(ERP.TipTopMaterial.CostDataInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CostDataInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CostDataInResult;
        
        public CostDataInResponseBody() {
        }
        
        public CostDataInResponseBody(string CostDataInResult) {
            this.CostDataInResult = CostDataInResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CostDataWSSoapChannel : ERP.TipTopMaterial.CostDataWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CostDataWSSoapClient : System.ServiceModel.ClientBase<ERP.TipTopMaterial.CostDataWSSoap>, ERP.TipTopMaterial.CostDataWSSoap {
        
        public CostDataWSSoapClient() {
        }
        
        public CostDataWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CostDataWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CostDataWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CostDataWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP.TipTopMaterial.CostDataInResponse ERP.TipTopMaterial.CostDataWSSoap.CostDataIn(ERP.TipTopMaterial.CostDataInRequest request) {
            return base.Channel.CostDataIn(request);
        }
        
        public string CostDataIn(string type, string buCode, string dotype, ERP.TipTopMaterial.ArrayOfString XMLS) {
            ERP.TipTopMaterial.CostDataInRequest inValue = new ERP.TipTopMaterial.CostDataInRequest();
            inValue.Body = new ERP.TipTopMaterial.CostDataInRequestBody();
            inValue.Body.type = type;
            inValue.Body.buCode = buCode;
            inValue.Body.dotype = dotype;
            inValue.Body.XMLS = XMLS;
            ERP.TipTopMaterial.CostDataInResponse retVal = ((ERP.TipTopMaterial.CostDataWSSoap)(this)).CostDataIn(inValue);
            return retVal.Body.CostDataInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP.TipTopMaterial.CostDataInResponse> ERP.TipTopMaterial.CostDataWSSoap.CostDataInAsync(ERP.TipTopMaterial.CostDataInRequest request) {
            return base.Channel.CostDataInAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP.TipTopMaterial.CostDataInResponse> CostDataInAsync(string type, string buCode, string dotype, ERP.TipTopMaterial.ArrayOfString XMLS) {
            ERP.TipTopMaterial.CostDataInRequest inValue = new ERP.TipTopMaterial.CostDataInRequest();
            inValue.Body = new ERP.TipTopMaterial.CostDataInRequestBody();
            inValue.Body.type = type;
            inValue.Body.buCode = buCode;
            inValue.Body.dotype = dotype;
            inValue.Body.XMLS = XMLS;
            return ((ERP.TipTopMaterial.CostDataWSSoap)(this)).CostDataInAsync(inValue);
        }
    }
}
