//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Sys {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Sys.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string CreateDateTime {
            get {
                return ResourceManager.GetString("CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建人 的本地化字符串。
        /// </summary>
        internal static string CreateUserID {
            get {
                return ResourceManager.GetString("CreateUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除选中行？ 的本地化字符串。
        /// </summary>
        internal static string DeleteRecordQuestion {
            get {
                return ResourceManager.GetString("DeleteRecordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先保存数据 的本地化字符串。
        /// </summary>
        internal static string SaveDataFirst {
            get {
                return ResourceManager.GetString("SaveDataFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统名称 的本地化字符串。
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统代码 的本地化字符串。
        /// </summary>
        internal static string SystemCode {
            get {
                return ResourceManager.GetString("SystemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统代码不能为空 的本地化字符串。
        /// </summary>
        internal static string SystemCodeCanNotBlank {
            get {
                return ResourceManager.GetString("SystemCodeCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该系统代码已经存在 的本地化字符串。
        /// </summary>
        internal static string SystemCodeExist {
            get {
                return ResourceManager.GetString("SystemCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统描述 的本地化字符串。
        /// </summary>
        internal static string SystemDescription {
            get {
                return ResourceManager.GetString("SystemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统名称 的本地化字符串。
        /// </summary>
        internal static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统名称不能为空 的本地化字符串。
        /// </summary>
        internal static string SystemNameCanNotBlank {
            get {
                return ResourceManager.GetString("SystemNameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 员工 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
