//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SysMenu {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysMenu.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增同级节点 的本地化字符串。
        /// </summary>
        internal static string AddSiblingNode {
            get {
                return ResourceManager.GetString("AddSiblingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增下一级节点 的本地化字符串。
        /// </summary>
        internal static string AddSubNode {
            get {
                return ResourceManager.GetString("AddSubNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码 的本地化字符串。
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码不能为空 的本地化字符串。
        /// </summary>
        internal static string CodeCanNotBlank {
            get {
                return ResourceManager.GetString("CodeCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请从叶子节点开始删除 的本地化字符串。
        /// </summary>
        internal static string DeleteFromLeaf {
            get {
                return ResourceManager.GetString("DeleteFromLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你真的要删除该记录吗？ 的本地化字符串。
        /// </summary>
        internal static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你真的要删除该记录吗？ 的本地化字符串。
        /// </summary>
        internal static string DeleteRecordQuestion {
            get {
                return ResourceManager.GetString("DeleteRecordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否展开 的本地化字符串。
        /// </summary>
        internal static string Expanded {
            get {
                return ResourceManager.GetString("Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图标 的本地化字符串。
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可用性 的本地化字符串。
        /// </summary>
        internal static string IsEnable {
            get {
                return ResourceManager.GetString("IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可见性 的本地化字符串。
        /// </summary>
        internal static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单名称 的本地化字符串。
        /// </summary>
        internal static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单名称不能为空 的本地化字符串。
        /// </summary>
        internal static string MenuNameCanNotBlank {
            get {
                return ResourceManager.GetString("MenuNameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 英文菜单 的本地化字符串。
        /// </summary>
        internal static string MenuNameEn {
            get {
                return ResourceManager.GetString("MenuNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该菜单名称已经存在 的本地化字符串。
        /// </summary>
        internal static string MenuNameExist {
            get {
                return ResourceManager.GetString("MenuNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 繁体菜单 的本地化字符串。
        /// </summary>
        internal static string MenuNameTh {
            get {
                return ResourceManager.GetString("MenuNameTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称不能为空 的本地化字符串。
        /// </summary>
        internal static string NameCanNotBlank {
            get {
                return ResourceManager.GetString("NameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 节点代码 的本地化字符串。
        /// </summary>
        internal static string NodeCode {
            get {
                return ResourceManager.GetString("NodeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 节点代码不能为空 的本地化字符串。
        /// </summary>
        internal static string NodeCodeCanNotBlank {
            get {
                return ResourceManager.GetString("NodeCodeCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该节点代码已经存在 的本地化字符串。
        /// </summary>
        internal static string NodeExist {
            get {
                return ResourceManager.GetString("NodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选在一个菜单节点 的本地化字符串。
        /// </summary>
        internal static string SelectMenuNode {
            get {
                return ResourceManager.GetString("SelectMenuNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 排序号 的本地化字符串。
        /// </summary>
        internal static string SortNo {
            get {
                return ResourceManager.GetString("SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 员工 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
