//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Organization {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Organization.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增同级节点 的本地化字符串。
        /// </summary>
        internal static string AddSiblingNode {
            get {
                return ResourceManager.GetString("AddSiblingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增子节点 的本地化字符串。
        /// </summary>
        internal static string AddSubNode {
            get {
                return ResourceManager.GetString("AddSubNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 归属地 的本地化字符串。
        /// </summary>
        internal static string Affiliation {
            get {
                return ResourceManager.GetString("Affiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您不能再增加子节点了，与编码规则不符! 的本地化字符串。
        /// </summary>
        internal static string CanNotAddMoreNode {
            get {
                return ResourceManager.GetString("CanNotAddMoreNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您不能删除内置编码规则 的本地化字符串。
        /// </summary>
        internal static string CanNotDeleteFixedCodeRule {
            get {
                return ResourceManager.GetString("CanNotDeleteFixedCodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否默认 的本地化字符串。
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请从叶子节点开始删除 的本地化字符串。
        /// </summary>
        internal static string DeleteFromLeafNode {
            get {
                return ResourceManager.GetString("DeleteFromLeafNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你真的要删除该记录吗？ 的本地化字符串。
        /// </summary>
        internal static string DeleteNodeQuestion {
            get {
                return ResourceManager.GetString("DeleteNodeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否可选 的本地化字符串。
        /// </summary>
        internal static string EnableSelect {
            get {
                return ResourceManager.GetString("EnableSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 传真 的本地化字符串。
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该节点代码已经存在 的本地化字符串。
        /// </summary>
        internal static string NodeCodeExisted {
            get {
                return ResourceManager.GetString("NodeCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该节点已经存在 的本地化字符串。
        /// </summary>
        internal static string NodeExisted {
            get {
                return ResourceManager.GetString("NodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 组织代码 的本地化字符串。
        /// </summary>
        internal static string OrgCode {
            get {
                return ResourceManager.GetString("OrgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 组织编码不能为空 的本地化字符串。
        /// </summary>
        internal static string OrgCodeCanNotBlank {
            get {
                return ResourceManager.GetString("OrgCodeCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string OrgDescription {
            get {
                return ResourceManager.GetString("OrgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 组织名称 的本地化字符串。
        /// </summary>
        internal static string OrgName {
            get {
                return ResourceManager.GetString("OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 组织名称不能为空 的本地化字符串。
        /// </summary>
        internal static string OrgNameCanNotBlank {
            get {
                return ResourceManager.GetString("OrgNameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 简称 的本地化字符串。
        /// </summary>
        internal static string OrgShortName {
            get {
                return ResourceManager.GetString("OrgShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 组织类型 的本地化字符串。
        /// </summary>
        internal static string OrgType {
            get {
                return ResourceManager.GetString("OrgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码原则 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改失败 的本地化字符串。
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string UpdateNode {
            get {
                return ResourceManager.GetString("UpdateNode", resourceCulture);
            }
        }
    }
}
