//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CodeRule {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CodeRule.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增失败 的本地化字符串。
        /// </summary>
        internal static string AddFailed {
            get {
                return ResourceManager.GetString("AddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加内置规则 的本地化字符串。
        /// </summary>
        internal static string AddFixedRule {
            get {
                return ResourceManager.GetString("AddFixedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增同级节点 的本地化字符串。
        /// </summary>
        internal static string AddSiblingNode {
            get {
                return ResourceManager.GetString("AddSiblingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增子节点 的本地化字符串。
        /// </summary>
        internal static string AddSubNode {
            get {
                return ResourceManager.GetString("AddSubNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您不能再增加子节点了，与编码规则不符! 的本地化字符串。
        /// </summary>
        internal static string CanNotAddMoreNode {
            get {
                return ResourceManager.GetString("CanNotAddMoreNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您不能删除内置编码规则 的本地化字符串。
        /// </summary>
        internal static string CanNotDeleteFixedCodeRule {
            get {
                return ResourceManager.GetString("CanNotDeleteFixedCodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码原则代码 的本地化字符串。
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码原则代码不能为空 的本地化字符串。
        /// </summary>
        internal static string CodeCanNotBlank {
            get {
                return ResourceManager.GetString("CodeCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关联业务 的本地化字符串。
        /// </summary>
        internal static string ConnectBusiness {
            get {
                return ResourceManager.GetString("ConnectBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请从叶子节点开始删除 的本地化字符串。
        /// </summary>
        internal static string DeleteFromLeafNode {
            get {
                return ResourceManager.GetString("DeleteFromLeafNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你真的要删除该记录吗？ 的本地化字符串。
        /// </summary>
        internal static string DeleteNodeQuestion {
            get {
                return ResourceManager.GetString("DeleteNodeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 字段 的本地化字符串。
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 字段不能为空 的本地化字符串。
        /// </summary>
        internal static string FieldCanNotBlank {
            get {
                return ResourceManager.GetString("FieldCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内置规则 的本地化字符串。
        /// </summary>
        internal static string FixedRule {
            get {
                return ResourceManager.GetString("FixedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分组号 的本地化字符串。
        /// </summary>
        internal static string GroupNo {
            get {
                return ResourceManager.GetString("GroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否有效 的本地化字符串。
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否默认值 的本地化字符串。
        /// </summary>
        internal static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码原则 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码原则不能为空 的本地化字符串。
        /// </summary>
        internal static string NameCanNotBlank {
            get {
                return ResourceManager.GetString("NameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该节点代码已经存在 的本地化字符串。
        /// </summary>
        internal static string NodeCodeExisted {
            get {
                return ResourceManager.GetString("NodeCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该节点已经存在 的本地化字符串。
        /// </summary>
        internal static string NodeExisted {
            get {
                return ResourceManager.GetString("NodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数编码 的本地化字符串。
        /// </summary>
        internal static string ParameterCode {
            get {
                return ResourceManager.GetString("ParameterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数编码不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterCodeCanNotBlank {
            get {
                return ResourceManager.GetString("ParameterCodeCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string ParameterDescription {
            get {
                return ResourceManager.GetString("ParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数名称 的本地化字符串。
        /// </summary>
        internal static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数名称不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterNameCanNotBlank {
            get {
                return ResourceManager.GetString("ParameterNameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数类型 的本地化字符串。
        /// </summary>
        internal static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数值 的本地化字符串。
        /// </summary>
        internal static string ParameterValue {
            get {
                return ResourceManager.GetString("ParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你真的要删除该节点吗？ 的本地化字符串。
        /// </summary>
        internal static string QuestionDeleteNode {
            get {
                return ResourceManager.GetString("QuestionDeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 规则 的本地化字符串。
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 规则不能为空 的本地化字符串。
        /// </summary>
        internal static string RuleCanNotBlank {
            get {
                return ResourceManager.GetString("RuleCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 规则代码 的本地化字符串。
        /// </summary>
        internal static string RuleEN {
            get {
                return ResourceManager.GetString("RuleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 规则代码不能为空 的本地化字符串。
        /// </summary>
        internal static string RuleENCanNotBlank {
            get {
                return ResourceManager.GetString("RuleENCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库/表空间 的本地化字符串。
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库/表空间不能为空 的本地化字符串。
        /// </summary>
        internal static string SchemaCanNotBlank {
            get {
                return ResourceManager.GetString("SchemaCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择一个菜单节点 的本地化字符串。
        /// </summary>
        internal static string SelectMenuNode {
            get {
                return ResourceManager.GetString("SelectMenuNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 排序号 的本地化字符串。
        /// </summary>
        internal static string SortNo {
            get {
                return ResourceManager.GetString("SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 表名 的本地化字符串。
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 表名不能为空 的本地化字符串。
        /// </summary>
        internal static string TableNameCanNotBlank {
            get {
                return ResourceManager.GetString("TableNameCanNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编码原则 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改失败 的本地化字符串。
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string UpdateNode {
            get {
                return ResourceManager.GetString("UpdateNode", resourceCulture);
            }
        }
    }
}
